version: '3'
services:
  database:
    container_name: tinycounter-db
    image: postgres
    restart: always
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'tinycounter'
    ports:
      - '5432:5432'
